import {
    AlignVerticalJustifyEnd,
    ArrowLeft,
    ArrowRight, BadgeCheck,
    Book,
    Calendar, CarFront, Carrot,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsUpDown,
    CircleDollarSign,
    Cog,
    Database,
    EqualNotIcon,
    File as LucidFile,
    FileCheck2,
    FileImage,
    FileVideo2, Fish,
    Home,
    Info,
    LayoutDashboard,
    List,
    ListChecks,
    ListOrdered,
    Loader2,
    MapPin, Minus,
    MoreVertical,
    Pencil,
    Plus,
    Route,
    School, Search,
    ShieldCheck,
    ShoppingCart, Soup,
    Square,
    Star,
    Tags,
    Trash2,
    Upload,
    User,
    UserCircle,
    UserRoundCheck
} from "lucide-react"

export const Icons = {
    plus: Plus,
    minus: Minus,
    badgeCheck: BadgeCheck,
    checkCircle: CheckCircle,
    search: Search,
    soup: Soup,
    carrot: Carrot,
    car: CarFront,
    fish: Fish,
    arrowRight: ArrowRight,
    arrowLeft: ArrowLeft,
    list: List,
    upload: Upload,
    fileImage: FileImage,
    fileVideo2: FileVideo2,
    pencil: Pencil,
    trash2: Trash2,
    file: LucidFile,
    database: Database,
    info: Info,
    spinner: Loader2,
    check: Check,
    moreVertical: MoreVertical,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronsUpDown: ChevronsUpDown,
    chevronDown: ChevronDown,
    mapIn: MapPin,
    listChecks: ListChecks,
    fileCheck2: FileCheck2,
    userRoundCheck: UserRoundCheck,
    route:Route,
    dashboard: LayoutDashboard,
    school: School,
    class: Square,
    level: Star,
    course: Book,
    exam: Pencil,
    assessment: EqualNotIcon,
    employee: User,
    staff: UserCircle,
    planning: Calendar,
    circleDollarSign: CircleDollarSign,
    listOrdered: ListOrdered,
    shieldCheck: ShieldCheck,
    shoppingCart:ShoppingCart,
    users: User,
    cog: Cog,
    home: Home,
    alignVerticalJustifyEnd: AlignVerticalJustifyEnd,
    tags: Tags

}
